version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: dejaramillo
      POSTGRES_PASSWORD: d3j4r4m1ll0
      POSTGRES_DB: mock_rick_morty
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local